# Generated by Django 2.0.5 on 2018-05-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classmethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='教室名称')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='学生姓名')),
                ('email', models.CharField(max_length=64, verbose_name='学生邮箱')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Classmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='教师姓名')),
                ('email', models.CharField(max_length=64, verbose_name='教师邮箱')),
                ('classes', models.ManyToManyField(to='app01.Classmethod')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='用户姓名')),
                ('pwd', models.CharField(max_length=64, verbose_name='用户密码')),
            ],
        ),
    ]
